routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/* Route::get('/', function () {
    return view('welcome');
}); */

/*---------- Rutas Index --------------*/
Route::get('/', 'SendMailController@index')->name('inicio');
Route::post('email', 'SendMailController@store')->name('tv');
Route::post('atencion', 'SendMailController@customsupp')->name('atencion');
Route::post('inter', 'SendMailController@inter')->name('inter');
Route::post('coor', 'SendMailController@coor')->name('coor');
Route::get('speed', 'SpeedController@index')->name('speed');

// Búsqueda de Clientes
Route::get('tovar/search', 'OptionsRegisterController@tovarsearch')->name('tovar_search');
Route::post('tovar/search', 'OptionsRegisterController@tovarpost')->name('tovar_post');
Route::get('merida/search', 'OptionsRegisterController@meridasearch')->name('merida_search');
Route::post('merida/search', 'OptionsRegisterController@meridapost')->name('merida_post');


// Register Options
Route::get('options', 'OptionsRegisterController@index')->name('options');

// Authentication Routes...
Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('login', 'Auth\LoginController@login');
Route::post('logout', 'Auth\LoginController@logout')->name('logout');

// Registration Routes...
Route::get('register', 'Auth\RegisterController@showRegistrationForm')->name('register');
Route::post('register', 'Auth\RegisterController@register');

/**
 * Register the typical reset password routes for an application.
 */

Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
Route::post('password/reset', 'Auth\ResetPasswordController@reset')->name('password.update');

/**
 * Register the typical email verification routes for an application.
*/

Route::get('email/verify', 'Auth\VerificationController@show')->name('verification.notice');
Route::get('email/verify/{id}', 'Auth\VerificationController@verify')->name('verification.verify');
Route::get('email/resend', 'Auth\VerificationController@resend')->name('verification.resend');

Route::get('/home', 'HomeController@index')->name('home');


/*------------ Rutas de Admin Dashboard -----------------*/
Route::namespace('Admin')->middleware('admin')->group( function () {
    Route::get('listuser', 'AdminController@show')->name('listuser');
    Route::get('adm/register', 'AdminController@register')->name('admRegister');
    Route::post('adm/register', 'AdminController@postRegister')->name('postRegister');
    Route::get('adm/pagos', 'AdminController@listpay')->name('listpay');
    Route::get('export', 'AdminController@export')->name('export');
    Route::get('edit/users/{id}', 'AdminController@editUser')->name('edit.user');
    Route::put('edit/users/{id}', 'AdminController@editUserUpdate')->name('editUser.update');
    Route::delete('delete/users/{id}', 'AdminController@deleteUser')->name('delete.user'); 
    Route::put('approve/payment/{id}', 'AdminController@approve')->name('aprobar.pagos');
    Route::put('rejected/payment/{id}', 'AdminController@rejected')->name('rechazar.pagos');
});

Route::get('/home', 'HomeController@index')->name('home')->middleware('verified');

/*----------------- Rutas de los Usuarios --------------------*/
Route::group(['middleware' => 'auth'], function () {
    Route::get('deuda', 'UserOptionsController@debt')->name('debt');
    Route::get('pagar', 'UserOptionsController@pay')->name('pay');
    Route::get('provincial', 'BanksController@bp')->name('bp');
    Route::post('provincial/pago', 'BankPostController@bp')->name('bp_post');
    Route::get('mercantil/merida', 'BanksController@mm')->name('mm');
    Route::post('mercantil/merida/pago', 'BankPostController@mm')->name('mm_post');
    Route::get('mercantil/tovar', 'BanksController@mt')->name('mt');
    Route::post('mercantil/tovar/pago', 'BankPostController@mt')->name('mt_post');
    Route::get('venezuela', 'BanksController@bdv')->name('bdv');
    Route::post('venezuela/pago', 'BankPostController@bdv')->name('bdv_post');
    Route::get('banesco', 'BanksController@banesco')->name('banesco');
    Route::post('banesco/pago', 'BankPostController@banescopost')->name('banesco_post');
    Route::get('sofitasa', 'BanksController@bs')->name('bs');
    Route::post('sofitasa/pago', 'BankPostController@bs')->name('bs_post');
    Route::get('historico', 'UserOptionsController@history')->name('history');
    Route::get('invoice/{id}', 'UserOptionsController@invoice')->name('invoice');
    Route::get('print/{id}', 'UserOptionsController@print')->name('imprimir');
    Route::get('buscador', 'UserOptionsController@index')->name('buscador');
    Route::get('live_search', 'UserOptionsController@search')->name('hotSearch');
});

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use App\Notifications\ResetPasswordsNotification;
use App\Notifications\VerifyEmail;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Auth;

class User extends Authenticatable implements MustVerifyEmail
{
    use Notifiable;

    protected $connection = 'pgsql';

    protected $table = "users";

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password', 'ci', 'role', 'address'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    /**
     * Send the password reset notification.
     *
     * @param  string  $token
     * @return void
     */
    public function sendPasswordResetNotification($token)
    {
        $this->notify(new ResetPasswordsNotification($token));
    }

    public function getIsAdminAttribute()
    {
        return $this->role == 0;
    }

    public function getIsUserAttribute()
    {
        return $this->role == 1;
    }

    public function payments(){
        return $this->hasMany(Payment::class, 'user_id');
    }
}

resources/views/admin/dashadmin.blade.php
@extends('admin.dashboard')

@section('content')

<div class="row">
  

	<div class="col-md-5">
      <!-- Widget: user widget style 1 -->
      <div class="box box-widget widget-user" style="margin-bottom: 30px;">
        <!-- Add the bg color to the header using any of the bg-* classes -->
        <div class="widget-user-header bg-aqua-active">
          <h3 class="widget-user-username">{{auth()->user()->name}}</h3>
          <h5 class="widget-user-desc">{{auth()->user()->email}}</h5>
        </div>
          <!-- /.row -->
      </div>
      <!-- small box -->
      @if (auth()->user()->is_admin)
          
          <div class="small-box bg-aqua">
            <div class="inner">
              <h3>{{$users}}</h3>

              <p>Usuarios Registrados</p>
            </div>
            <div class="icon">
              <i class="ion ion-person-add"></i>
            </div>
          </div>
      @endif
    </div>
      <!-- /.widget-user -->

@if (auth()->user()->is_admin)
  <div class="row" style="display: grid; padding-left: 15rem;">
    <!-- Small boxes (Stat box) -->
        <div class="col-md-8">
          <!-- small box -->
          <div class="small-box bg-yellow">
            <div class="inner">
              <h3>{{$pendiente}}</h3>

              <p>Pagos Pendientes</p>
            </div>
            <div class="icon">
              <i class="fas fa-file-invoice-dollar"></i>
            </div>
          </div>
        </div>
        <!-- ./col -->
        <div class="col-md-8">
          <!-- small box -->
          <div class="small-box bg-green">
            <div class="inner">
              <h3>{{$hechos}}</h3>

              <p>Pagos Aprobados</p>
            </div>
            <div class="icon">
              <i class="ion ion-stats-bars"></i>
            </div>
          </div>
        </div>
        <!-- ./col -->
        <div class="col-md-8">
          <!-- small box -->
          <div class="small-box bg-red">
            <div class="inner">
              <h3>{{$reject}}</h3>

              <p>Pagos Rechazados</p>
            </div>
            <div class="icon">
              <i class="fas fa-ban"></i>
            </div>
          </div>
        </div>
        <!-- ./col -->
        <div class="col-md-8">
          <div class="small-box bg-aqua">
            <div class="inner">
              <h3>{{$payment}}</h3>

              <p>Pagos Realizados</p>
            </div>
            <div class="icon">
              <i class="fas fa-cash-register"></i>
            </div>
          </div>
        </div>  
  </div>
@endif
</div>



@endsection

resources/views/admin/dashboard.blade.php
<!DOCTYPE html>
<!--
This is a starter template page. Use this page to start your new project from
scratch. This page gets rid of all links and provides the needed markup only.
-->
<html>
  
@include('layouts.head')

<!--
BODY TAG OPTIONS:
=================
Apply one or more of the following classes to get the
desired effect
|---------------------------------------------------------|
| SKINS         | skin-blue                               |
|               | skin-black                              |
|               | skin-purple                             |
|               | skin-yellow                             |
|               | skin-red                                |
|               | skin-green                              |
|---------------------------------------------------------|
|LAYOUT OPTIONS | fixed                                   |
|               | layout-boxed                            |
|               | layout-top-nav                          |
|               | sidebar-collapse                        |
|               | sidebar-mini                            |
|---------------------------------------------------------|
-->
<body class="hold-transition skin-blue sidebar-mini">

  <div class="wrapper">
  <!-- Main Header -->
  @include('layouts.header')
  <!-- Left side column. contains the logo and sidebar -->
  <aside class="main-sidebar">

    <!-- sidebar: style can be found in sidebar.less -->
    <section class="sidebar">

      <!-- Sidebar user panel (optional) -->
      <div class="user-panel">
        <div class="pull-left image">
          <i class="far fa-address-card"></i>
        </div>
        <div class="pull-left info">
          <p>{{auth()->user()->name}}</p>
          <!-- Status -->
        </div>
      </div>

      <!-- Sidebar Menu -->
      <ul class="sidebar-menu" data-widget="tree">
        <li class="header"></li>
        <!-- Optionally, you can add icons to the links -->
          <li><a href="{{ route('home') }}"><i class="fas fa-home"></i><span style="padding-left: .75rem;">Inicio</span></a></li>
          @if (auth()->user()->is_admin)
            <li><a href="{{ route('admRegister') }}"><i class="fas fa-user-plus"></i><span style="padding-left: .6rem;">Registrar Usuario</span></a></li>
            <li><a href="{{ route('listuser') }}"><i class="fas fa-address-book"></i><span style="padding-left: 1.2rem;">Listar Clientes</span></a></li>
            <li><a href="{{ route('listpay') }}"><i class="fas fa-search-dollar"></i><span style="padding-left: 1.2rem;">Listar Pagos</span></a></li>
            <li><a href="{{ route('export') }}"><i class="fas fa-file-excel"></i><span style="padding-left: 1.2rem;">Generar EXCEL</span></a></li>
          @else
            <li><a href="{{ route('debt') }}"><i class="fas fa-donate"></i><span style=" padding-left: 1rem;">Consultar Saldo</span></a></li>
            <li><a href="{{ route('pay') }}"><i class="fa fa-money"></i><span style=" padding-left: 1rem;">Pago en Línea</span></a></li>
            <li><a href="{{ route('history') }}"><i class="fa fa-history"></i><span style=" padding-left: 1rem;">Historicos de Pagos</span></a></li>
            <li><a href="{{ route('buscador') }}"><i class="fa fa-search-dollar"></i><span style=" padding-left: 1rem;">Buscar Pagos</span></a></li>
          @endif
      </ul>
      <!-- /.sidebar-menu -->
    </section>
    <!-- /.sidebar -->
  </aside>

  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <h1>
        Sistema de Pagos en Línea de Tovarsat C.A
      </h1>
    </section>

    <!-- Main content -->
    <section class="content container-fluid">
      @yield('content')

      @yield('listuser')

      @yield('saldo')

      @yield('nopagar')

      @yield('pagar')

      @yield('provincial')
      
      @yield('ppagos')

      @yield('history')

      @yield('invoice')
      
      @yield('buscar')

      @yield('registrar')

      @yield('listpay')

      @yield('edit-user')
    </section>
    
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->

  <!-- Main Footer -->
  <footer class="main-footer">
    <!-- Default to the left -->
    <strong>Copyright &copy; 1994 <a href="#">Tovarsat C.A</a>.</strong> All rights reserved.
  </footer>

  <!-- Add the sidebar's background. This div must be placed
  immediately after the control sidebar -->
  <div class="control-sidebar-bg"></div>
  </div>
<!-- ./wrapper -->

<!-- REQUIRED JS SCRIPTS -->
<!-- jQuery 3 -->
<script src="{{ asset('admin/bower_components/jquery/dist/jquery.js') }}"></script>
<!-- Bootstrap 3.3.7 -->
<script src="{{ asset('admin/bower_components/bootstrap/dist/js/bootstrap.js') }}"></script>
<!-- AdminLTE App -->
<script src=" {{ asset('admin/dist/js/adminlte.js') }}"></script>
<!-- FastClick -->
<script src="{{ asset('admin/bower_components/fastclick/lib/fastclick.js') }}"></script>
<!-- DataTables -->
<script src="{{ asset('admin/bower_components/datatables.net/js/jquery.dataTables.js')}}"></script>
<script src="{{ asset('admin/bower_components/datatables/js/dataTables.bootstrap.js')}}"></script>
<!-- AdminLTE for demo purposes -->
<script src="{{ asset('admin/dist/js/demo.js') }}"></script>
<!-- SlimScroll -->
<script src="{{ asset('admin/bower_components/jquery-slimscroll/jquery.slimscroll.js') }}"></script>
<!-- page script -->
<script>
  $(function () {
    $('#history').DataTable({
      'paging'      : false,
      'lengthChange': true,
      'searching'   : true,
      'ordering'    : true,
      'info'        : false,
      'autoWidth'   : true
    })
  })
</script>

<script>
  $(function () {
    $('#list-user').DataTable({
      'paging'      : false,
      'lengthChange': true,
      'searching'   : true,
      'ordering'    : true,
      'info'        : false,
      'autoWidth'   : true
    })
  })
</script>

<script>
  $(function () {
    $('#table-hotSearch').DataTable({
      'paging'      : true,
      'lengthChange': true,
      'searching'   : false,
      'ordering'    : true,
      'info'        : false,
      'autoWidth'   : true
    })
  })
</script>

<script>
  $(function () {
    $('#payment').DataTable({
      'paging'      : true,
      'lengthChange': false,
      'searching'   : true,
      'ordering'    : true,
      'info'        : false,
      'autoWidth'   : false
    })
  })
</script>

<script>

const buscador = document.querySelector('#resultados')

function traer() {

  var valor = document.getElementById("hotSearch").value

  if(valor.length >=2){
    fetch(`{{route("hotSearch")}}?hotSearch=${valor}`)
    .then(response => response.json())
    .then(tabla)
  }else{
    resultados.innerHTML = ''
  }
}

function tabla(data) {

  const options = { weekday: 'short', year: 'numeric', month: 'long', day: 'numeric' };

  for(let datos in data){

    var date = new Date(data[datos].created_at)
    var mydate = date.toLocaleDateString("es-ES", options)
    
    resultados.innerHTML += `
      <tr>
        <td>${data[datos].bank}</td>
        <td>${data[datos].brn}</td>
        <td>${data[datos].amount}</td>
        <td>${mydate}</td>
      </tr>
    `
  }
}
</script>
</body>
</html>

resources/views/admin/edituser.blade.php
@extends('admin.dashboard')

@section('edit-user')
<div class="register-box">

  <div class="register-box-body">
    @if (session()->has('crear'))
        <div class="alert alert-success alert-dismissible">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            <h5><i class="icon fa fa-check"></i>{{ session()->get('crear') }}</h5>
        </div>    
    @endif
    <p class="login-box-msg">Editar Usuario</p>

    <form action="{{ route('editUser.update', ['id' => $user]) }}" method="post">
        @method('put')
        @csrf
      <div class="form-group has-feedback">
        <input type="text" class="form-control" name="name" placeholder="Nombre Completo" value="{{old('name',$user->name)}}">
        <span class="glyphicon glyphicon-user form-control-feedback"></span>
        @error('name')
            <span class="invalid-feedback" role="alert">
                <strong>{{ $message }}</strong>
            </span>
        @enderror
      </div>
      <div class="form-group has-feedback">
        <input type="email" class="form-control" name="email" placeholder="Email" value="{{old('email',$user->email)}}">
        <span class="glyphicon glyphicon-envelope form-control-feedback"></span>
        @error('email')
            <span class="invalid-feedback" role="alert">
                <strong>{{ $message }}</strong>
            </span>
        @enderror
      </div>
      <div class="form-group has-feedback">
        <input type="text" class="form-control" name="ci" placeholder="Cédula" value="{{old('ci',$user->ci)}}" readonly>
        <span class="glyphicon glyphicon-credit-card form-control-feedback"></span>
        @error('ci')
            <span class="invalid-feedback" role="alert">
                <strong>{{ $message }}</strong>
            </span>
        @enderror
      </div>
      <div class="form-group">
        <label>Rol del Usuario</label>
        <select class="form-control" name="role" >
            <option>Usuario</option>
            <option>Administrador</option>
            </select>
        </div>
      <div class="form-group has-feedback">
        <input type="password" name="password" class="form-control" placeholder="Password">
        <span class="glyphicon glyphicon-lock form-control-feedback"></span>
        @error('password')
            <span class="invalid-feedback" role="alert">
                <strong>{{ $message }}</strong>
            </span>
        @enderror
      </div>
      <div class="form-group has-feedback">
        <input type="password" name="password_confirmation" class="form-control" placeholder="Repita password">
        <span class="glyphicon glyphicon-log-in form-control-feedback"></span>
        @error('password_confirmation')
            <span class="invalid-feedback" role="alert">
                <strong>{{ $message }}</strong>
            </span>
        @enderror
      </div>
      <div class="row">
        <!-- /.col -->
        <div class="col-xs-4">
          <button type="submit" class="btn btn-primary btn-block btn-flat">Editar</button>
        </div>
        <!-- /.col -->
      </div>
    </form>
  </div>
  <!-- /.form-box -->
</div>
<!-- /.register-box -->
    
@endsection

resources/views/admin/listuser.blade.php
@extends('admin.dashboard')

@section('listuser')
<div class="row">
        <div class="col-xs-12">
          @if (session()->has('msg'))
            <div class="alert alert-success alert-dismissible">
              <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
              <h5><i class="icon fa fa-check"></i>{{ session()->get('msg') }}</h5>
            </div>
          @elseif(session()->has('delete'))
            <div class="alert alert-danger alert-dismissible">
              <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
              <h5><i class="icon fa fa-warning"></i>{{ session()->get('delete') }}</h5>
            </div>
          @endif
          <div class="box" style="margin-bottom: 7px;">
            <div class="box-header">
              <h3 class="box-title">Listado de usuarios</h3>
            </div>
            <!-- /.box-header -->
            <div class="box-body">
              <table id="list-user" class="table table-bordered table-hover">
                <thead>
                  <tr>
                    <th>Nombre y Apellido</th>
                    <th>Cédula</th>
                    <th>Correo</th>
                    <th>Editar</th>
                  </tr>
                </thead>
                <tbody>
                  @foreach ($users as $user)
                    <tr>
                      <td>{{$user->name}}</td>
                      <td>{{$user->ci}} </td>
                      <td>{{$user->email}} </td>
                      <td><a href="{{ route('edit.user', ['id' => $user]) }}" class="btn btn-primary"> Editar</a></td>
                    </tr>    
                  @endforeach
                  
                </tbody>
              </table>
            </div>
          </div>
          {{ $users->links() }}
        <span style="display: flex;">Se muestran {{ $users->count() }} elementos de {{ $users->total() }} en total</span>
    </div>
</div>
@endsection

resources/views/admin/pagos.blade.php
@extends('admin.dashboard')

@section('listpay')
<div class="row">
        <div class="col-xs-12">
          @if (session()->has('approved'))
            <div class="alert alert-success alert-dismissible">
              <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
              <h5><i class="icon fa fa-check"></i><strong>{{ session()->get('approved') }}</strong></h5>
            </div>
          @elseif(session()->has('rejected'))
            <div class="alert alert-danger alert-dismissible">
              <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
              <h5><i class="icon fa fa-warning"></i><strong>{{ session()->get('rejected') }}</strong></h5>
            </div>              
          @endif
          <div class="box" style="margin-bottom: 7px;">
            <div class="box-header">
              <h3 class="box-title">Listado de Pagos</h3>
            </div>
            <!-- /.box-header -->
            <div class="box-body">
              <table id="payment" class="table table-bordered table-hover">
                <thead>
                  <tr>
                    <th>Banco al que se hizo la Transferencia</th>
                    <th>Referencia</th>
                    <th>Monto</th>
                    <th>Fecha en la que hizo la Transferencia</th>
                    <th>Usuario</th>
                    <th>Cédula</th>
                    <th>Sucursal</th>
                    <th>Estado</th>
                    <th>Aprobar</th>
                    <th>Rechazar</th>
                  </tr>
                </thead>
                <tbody>
                  @foreach ($pagos as $pago)
                    @foreach ($pago->payments as $item)
                      <tr>
                        <td>{{$item->bank}}</td>
                        <td>{{$item->brn}} </td>
                        <td>{{number_format($item->amount, '2', ',', '.')}}</td>
                        <td>{{Carbon\Carbon::parse($item->date)->locale('es')->translatedFormat('d F Y')}}</td>
                        @if ($item->user_id === $pago->id)
                          <td>{{$pago->name}} </td>
                          <td>{{$pago->ci}} </td>
                        @endif
                        <td>{{$pago->address}}</td>
                        @if ($item->status === 0)
                                <td><span class="label label-warning">Pendiente</span></td>
                        @elseif($item->status === 1)
                                <td><span class="label label-success">Aprobado</span></td>
                        @else
                                <td><span class="label label-danger">Rechazado</span></td>
                        @endif
                        <form action="{{ route('aprobar.pagos', ['id'=>$item]) }}" method="post">
                          @csrf
                          @method('put')
                          <td> <button name="approved" class="btn btn-success"> Aprobar</button></td>
                        </form>
                        <form action="{{ route('rechazar.pagos', ['id'=>$item]) }}" method="post">
                          @csrf
                          @method('put')
                          <td> <button name="rejected" class="btn btn-danger"> Rechazar</button></td>
                        </form>
                      </tr> 
                    @endforeach
                  @endforeach
                  
                </tbody>
              </table>
            </div>
          </div>
    </div>
</div>
    
@endsection

resources/views/admin/registrar.blade.php
@extends('admin.dashboard')

@section('registrar')

<div class="register-box">

  <div class="register-box-body">
    @if (session()->has('crear'))
        <div class="alert alert-success alert-dismissible">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            <h5><i class="icon fa fa-check"></i>{{ session()->get('crear') }}</h5>
        </div>    
    @endif
    <p class="login-box-msg">Registrar un nuevo Usuario</p>

    <form action="{{ route('postRegister') }}" method="post">
    @csrf
      <div class="form-group has-feedback">
        <input type="text" class="form-control" name="name" placeholder="Nombre Completo">
        <span class="glyphicon glyphicon-user form-control-feedback"></span>
        @error('name')
            <span class="invalid-feedback" role="alert">
                <strong>{{ $message }}</strong>
            </span>
        @enderror
      </div>
      <div class="form-group has-feedback">
        <input type="email" class="form-control" name="email" placeholder="Email">
        <span class="glyphicon glyphicon-envelope form-control-feedback"></span>
        @error('email')
            <span class="invalid-feedback" role="alert">
                <strong>{{ $message }}</strong>
            </span>
        @enderror
      </div>
      <div class="form-group has-feedback">
        <input type="text" class="form-control" name="ci" placeholder="Cédula">
        <span class="glyphicon glyphicon-credit-card form-control-feedback"></span>
        @error('ci')
            <span class="invalid-feedback" role="alert">
                <strong>{{ $message }}</strong>
            </span>
        @enderror
      </div>
      <div class="form-group">
        <label>Rol del Usuario</label>
        <select class="form-control" name="role" >
            <option>Usuario</option>
            <option>Administrador</option>
            </select>
        </div>
      <div class="form-group has-feedback">
        <input type="password" name="password" class="form-control" placeholder="Password">
        <span class="glyphicon glyphicon-lock form-control-feedback"></span>
        @error('password')
            <span class="invalid-feedback" role="alert">
                <strong>{{ $message }}</strong>
            </span>
        @enderror
      </div>
      <div class="form-group has-feedback">
        <input type="password" name="password_confirmation" class="form-control" placeholder="Repita password">
        <span class="glyphicon glyphicon-log-in form-control-feedback"></span>
        @error('password_confirmation')
            <span class="invalid-feedback" role="alert">
                <strong>{{ $message }}</strong>
            </span>
        @enderror
      </div>
      <div class="row">
        <!-- /.col -->
        <div class="col-xs-4">
          <button type="submit" class="btn btn-primary btn-block btn-flat">Registrar</button>
        </div>
        <!-- /.col -->
      </div>
    </form>
  </div>
  <!-- /.form-box -->
</div>
<!-- /.register-box -->
@endsection